name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag psycho007/url-shortener:$(date +%s)

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set this secret in GitHub
        password: ${{ secrets.DOCKER_PASSWORD }} 

   - name: Build and push Docker image
     uses: docker/build-push-action@v5
     with:
     context: .  # Use the current directory as the build context
     push: true  # Push the image to the registry
     tags: |
      psycho007/url-shortener:latest
      psycho007/url-shortener:${github.sha}
